export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const UNLOCKED_ACHIEVEMENT_MODAL = 'UNLOCKED_ACHIEVEMENT_MODAL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USERNAME_LOGIN_FAIL = 'USERNAME_LOGIN_FAIL';
export const PASSWORD_LOGIN_FAIL = 'PASSWORD_LOGIN_FAIL';
export const GET_LOGGED_IN_PERSON_SUCCESS = 'GET_LOGGED_IN_PERSON_SUCCESS';
export const GET_LOGGED_IN_PERSON_FAIL = 'GET_LOGGED_IN_PERSON_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SET_INITIAL_LOGIN_SUCCESS = 'SET_INITIAL_LOGIN_SUCCESS';

export const RESET_UPDATE_PERSON_DETAILS_SUCCESS = 'RESET_UPDATE_PERSON_DETAILS_SUCCESS';
export const UPDATE_PERSON_DETAILS_SUCCESS = 'UPDATE_PERSON_DETAILS_SUCCESS';
export const UPDATE_PERSON_DETAILS_FAIL = 'UPDATE_PERSON_DETAILS_FAIL';
export const UPDATE_PERSON_AVATAR_SUCCESS = 'UPDATE_PERSON_AVATAR_SUCCESS';
export const UPDATE_PERSON_AVATAR_FAIL = 'UPDATE_PERSON_AVATAR_FAIL';

export const CURRENT_PERSON_SCORE_SUCCESS = 'CURRENT_PERSON_SCORE_SUCCESS';
export const CURRENT_PERSON_SCORE_FAIL = 'CURRENT_PERSON_SCORE_FAIL';

export const GET_PERSONS_TOP_FIVE_ACTIVITIES_SUCCESS = 'GET_PERSONS_TOP_FIVE_ACTIVITIES_SUCCESS';
export const GET_PERSONS_TOP_FIVE_ACTIVITIES_FAIL = 'GET_PERSONS_TOP_FIVE_ACTIVITIES_FAIL';

export const GET_PERSONS_CHART_DATA_SUCCESS = 'GET_PERSONS_CHART_DATA_SUCCESS';
export const GET_PERSONS_CHART_DATA_FAIL = 'GET_PERSONS_CHART_DATA_FAIL';

export const SET_INITIAL_MOST_ACTIVE_USERS = 'SET_INITIAL_MOST_ACTIVE_USERS';
export const SET_INITIAL_PERSON_INFO = 'SET_INITIAL_PERSON_INFO';
export const GET_MOST_ACTIVE_USERS_SUCCESS = 'GET_MOST_ACTIVE_USERS_SUCCESS';
export const GET_MOST_ACTIVE_USERS_FAIL = 'GET_MOST_ACTIVE_USERS_FAIL';

export const TIMELINE_HEADING_MOTIVATIONAL_QUOTE_SUCCESS = 'TIMELINE_HEADING_MOTIVATIONAL_QUOTE_SUCCESS';
export const TIMELINE_HEADING_MOTIVATIONAL_QUOTE_FAIL = 'TIMELINE_HEADING_MOTIVATIONAL_QUOTE_FAIL';

export const TIMELINE_SCORE_MOTIVATIONAL_QUOTE_SUCCESS = 'TIMELINE_SCORE_MOTIVATIONAL_QUOTE_SUCCESS';
export const TIMELINE_SCORE_MOTIVATIONAL_QUOTE_FAIL = 'TIMELINE_SCORE_MOTIVATIONAL_QUOTE_FAIL';

export const DASHBOARD_MOTIVATIONAL_QUOTE_SUCCESS = 'DASHBOARD_MOTIVATIONAL_QUOTE_SUCCESS';
export const DASHBOARD_MOTIVATIONAL_QUOTE_FAIL = 'DASHBOARD_MOTIVATIONAL_QUOTE_FAIL';

export const LOGIN_MOTIVATIONAL_QUOTE_SUCCESS = 'LOGIN_MOTIVATIONAL_QUOTE_SUCCESS';
export const LOGIN_MOTIVATIONAL_QUOTE_FAIL = 'LOGIN_MOTIVATIONAL_QUOTE_FAIL';

export const GET_TIMELINE_ALL_SUCCESS = 'GET_TIMELINE_ALL_SUCCESS';
export const GET_TIMELINE_ALL_FAIL = 'GET_TIMELINE_ALL_FAIL';
export const GET_NEXT_TIMELINE_SUCCESS = 'GET_NEXT_TIMELINE_SUCCESS';
export const GET_NEXT_TIMELINE_FAIL = 'GET_NEXT_TIMELINE_FAIL';
export const APPEND_NEXT_TO_CURRENT_TIMELINE = 'APPEND_NEXT_TO_CURRENT_TIMELINE';
export const SET_INITIAL_TIMELINE_ACTIVITIES = 'SET_INITIAL_TIMELINE_ACTIVITIES';

export const RELOAD_PERSON_DAILY_ACTIVITY_CONGRATULATORS_SUCCESS = 'RELOAD_PERSON_DAILY_ACTIVITY_CONGRATULATORS_SUCCESS';
export const RELOAD_PERSON_DAILY_ACTIVITY_CONGRATULATORS_FAIL = 'RELOAD_PERSON_DAILY_ACTIVITY_FAIL';

export const SET_TIMELINE_PAGE_SUCCESS = 'SET_TIMELINE_PAGE_SUCCESS';
export const SET_IMAGE_URL_SUCCESS = 'SET_IMAGE_URL_SUCCESS';

export const SET_CALENDAR_INITIAL_STATE = 'SET_CALENDAR_INITIAL_STATE';
export const FETCH_CALENDAR_ACTIVITIES_SUCCESS = 'FETCH_CALENDAR_ACTIVITIES_SUCCESS';
export const FETCH_CALENDAR_ACTIVITIES_FAIL = 'FETCH_CALENDAR_ACTIVITIES_FAIL';

export const FETCH_ALL_GROUPED_ACTIVITIES_SUCCESS = 'FETCH_ALL_GROUPED_ACTIVITIES_SUCCESS';
export const FETCH_ALL_GROUPED_ACTIVITIES_FAIL = 'FETCH_ALL_GROUPED_ACTIVITIES_FAIL';

export const UPDATE_PERSON_DAILY_ACTIVITY_SUCCESS = 'UPDATE_PERSON_DAILY_ACTIVITY_SUCCESS';
export const UPDATE_PERSON_DAILY_ACTIVITY_FAIL = 'UPDATE_PERSON_DAILY_ACTIVITY_FAIL';

export const CREATE_PERSON_DAILY_ACTIVITY_SUCCESS = 'UPDATE_PERSON_DAILY_ACTIVITY_SUCCESS';
export const CREATE_PERSON_DAILY_ACTIVITY_FAIL = 'UPDATE_PERSON_DAILY_ACTIVITY_FAIL';

export const RESET_PERSON_DAILY_ACTIVITY_SUCCESS = 'RESET_PERSON_DAILY_ACTIVITY_SUCCESS';

export const GET_LAST_MONTH_ACTIVITY_STATISTICS_SUCCESS = 'GET_LAST_MONTH_ACTIVITY_STATISTICS_SUCCESS';
export const GET_LAST_MONTH_ACTIVITY_STATISTICS_FAIL = 'GET_LAST_MONTH_ACTIVITY_STATISTICS_FAIL';

export const GET_SELECTED_USER_INFO_SUCCESS = 'GET_SELECTED_USER_INFO_SUCCESS';
export const GET_SELECTED_USER_INFO_FAIL = 'GET_SELECTED_USER_INFO_FAIL';

export const SET_SELECTED_USER_ID = 'SET_SELECTED_USER_ID';

export const SET_INITIAL_ACHIEVEMENTS_STATE = 'SET_INITIAL_ACHIEVEMENTS_STATE';

export const FETCH_PERSONS_COMPLETED_ACHIEVEMENTS_SUCCESS = 'FETCH_PERSONS_COMPLETED_ACHIEVEMENTS_SUCCESS';
export const FETCH_PERSONS_COMPLETED_ACHIEVEMENTS_FAIL = 'FETCH_PERSONS_COMPLETED_ACHIEVEMENTS_FAIL';
export const FETCH_PERSONS_LOCKED_ACHIEVEMENTS_SUCCESS = 'FETCH_PERSONS_LOCKED_ACHIEVEMENTS_SUCCESS';
export const FETCH_PERSONS_LOCKED_ACHIEVEMENTS_FAIL = 'FETCH_PERSONS_LOCKED_ACHIEVEMENTS_FAIL';
export const FETCH_PERSONS_COMPLETED_ACHIEVEMENTS_MONTHLY_SUCCESS = 'FETCH_PERSONS_COMPLETED_ACHIEVEMENTS_MONTHLY_SUCCESS';
export const FETCH_PERSONS_COMPLETED_ACHIEVEMENTS_MONTHLY_FAIL = 'FETCH_PERSONS_COMPLETED_ACHIEVEMENTS_MONTHLY_FAIL';

export const SET_INITIAL_SCORES_STATE = 'SET_INITIAL_SCORES_STATE';

export const GET_TOP_THREE_PERSONS_SUCCESS = 'GET_TOP_THREE_PERSONS_SUCCESS';
export const GET_TOP_THREE_PERSONS_FAIL = 'GET_TOP_THREE_PERSONS_FAIL';
export const GET_TOP_PERSONS_CURRENT_MONTH_SUCCESS = 'GET_TOP_PERSONS_CURRENT_MONTH_SUCCESS';
export const GET_TOP_PERSONS_CURRENT_MONTH_FAIL = 'GET_TOP_PERSONS_CURRENT_MONTH_FAIL';
export const GET_TOP_PERSONS_LAST_MONTH_SUCCESS = 'GET_TOP_PERSONS_LAST_MONTH_SUCCESS';
export const GET_TOP_PERSONS_LAST_MONTH_FAIL = 'GET_TOP_PERSONS_LAST_MONTH_FAIL';
export const GET_TOP_PERSONS_LAST_THREE_MONTHS_SUCCESS = 'GET_TOP_PERSONS_LAST_THREE_MONTHS_SUCCESS';
export const GET_TOP_PERSONS_LAST_THREE_MONTHS_FAIL = 'GET_TOP_PERSONS_LAST_THREE_MONTHS_FAIL';
export const GET_TOP_PERSONS_LAST_YEAR_SUCCESS = 'GET_TOP_PERSONS_LAST_YEAR_SUCCESS';
export const GET_TOP_PERSONS_LAST_YEAR_FAIL = 'GET_TOP_PERSONS_LAST_YEAR_FAIL';

export const GET_PERSON_DAILY_ACTIVITY_ENCRYPTED_ID_SUCCESS = 'GET_PERSON_DAILY_ACTIVITY_ENCRYPTED_ID_SUCCESS';
export const GET_PERSON_DAILY_ACTIVITY_ENCRYPTED_ID_FAIL = 'GET_PERSON_DAILY_ACTIVITY_ENCRYPTED_ID_FAIL';
export const CONFIRM_MVP_ACTIVITIES_SUCCESS = 'CONFIRM_MVP_ACTIVITIES_SUCCESS';
export const CONFIRM_MVP_ACTIVITIES_FAIL = 'CONFIRM_MVP_ACTIVITIES_FAIL';
export const DECLINE_MVP_ACTIVITIES_SUCCESS = 'DECLINE_MVP_ACTIVITIES_SUCCESS';
export const DECLINE_MVP_ACTIVITIES_FAIL = 'DECLINE_MVP_ACTIVITIES_FAIL';

export const RECEIVED_NEW_ACHIEVEMENTS = 'RECEIVED_NEW_ACHIEVEMENTS';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const FETCH_MONTH_SCORE_SUCCESS = 'FETCH_MONTH_SCORE_SUCCESS';
export const FETCH_MONTH_SCORE_FAIL = 'FETCH_MONTH_SCORE_FAIL';

export const FETCH_PROCESSED_MVP_ACTIVITIES_SUCCESS = 'FETCH_PROCESSED_MVP_ACTIVITIES_SUCCESS';
export const FETCH_PROCESSED_MVP_ACTIVITIES_FAIL = 'FETCH_PROCESSED_MVP_ACTIVITIES_FAIL';

export const REMOVE_SEEN_MVP_ACTIVITIES = 'REMOVE_SEEN_MVP_ACTIVITIES';
export const REMOVE_SEEN_MVP_ACTIVITIES_FAIL = 'REMOVE_SEEN_MVP_ACTIVITIES_FAIL';

